### ISSUE TITLE
CA Template Request - Kdenlive VNC

### ISSUE THREAD

**Issue by TessyPowder** [selfhosters/unRAID-CA-templates#101]
[Dockerhub](https://hub.docker.com/r/tessypowder/docker-kdenlive)
[GitHub](https://github.com/TessyPowder/kdenlive-vnc-docker)
[App XML](https://github.com/TessyPowder/unraid-docker-templates/blob/master/tessypowder/kdenlive-vnc.xml)

Its just an instance of Kdenlive, that can be acessed over http and vnc, to make it easier to use your server as a rendering server.

**Comment by TessyPowder** [comment]
I am not sure how this happened, but the name of my container got changed from "Kdenlive VNC" to "Kdenlive VPN". In my app xml the name is correct ("Kdenlive VNC"), can this please be changed ?

**Comment by christronyxyocum** [comment]
I'll fix it.

**Comment by TessyPowder** [comment]
thanks :)

**Comment by christronyxyocum** [comment]
Will be fixed once this is merged and it propogates to CA:

https://github.com/selfhosters/unRAID-CA-templates/pull/120
