### ISSUE TITLE
CA Template Request - Card's Against humanity clone (Xyzzy)

### ISSUE THREAD

**Issue by cjannusch** [selfhosters/unRAID-CA-templates#103]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/emcniece/dockeryourxyzzy/
https://github.com/emcniece/DockerYourXyzzy

#### Post any additional information about the project that you know is important 
original project here 
https://github.com/ajanata/PretendYoureXyzzy

**Comment by Roxedus** [comment]
I could not get this to run.

**Comment by christronyxyocum** [comment]
It was mostly last touched 2 years ago. Some of it even longer. I can't get it to function either.
