### ISSUE TITLE
CA Template Request - mwoffliner

### ISSUE THREAD

**Issue by GlassedSilver** [selfhosters/unRAID-CA-templates#104]
Command-line utility to create ZIM files from MediaWiki-based wikis.
ZIM files are offline backups of wikis and other pages and can be viewed by Kiwix, which already has a CA available. (kiwix.org)

***

**Please add the dockerhub repo link and github/gitlab link below**

- dockerhub: https://hub.docker.com/r/openzim/mwoffliner

- github: https://github.com/openzim/mwoffliner

#### Post any additional information about the project that you know is important 
It's a CLI application and I'm not very well versed with this application in particular, especially as it's got a very interesting docker deployment style. See: [Docker readme](https://github.com/openzim/mwoffliner/blob/master/docker/README.md)

Maybe someone could even add a simple webGUI wrapper/automation to this? I would have no idea how to do that, but anything that makes this a set and forget in the spirit of having this run unattended on a server would be a bonus obviously. Right now I think it's all manual.

Cheers and thanks for anyone looking into this.

**Comment by christronyxyocum** [comment]
> Maybe someone could even add a simple webGUI wrapper/automation to this? I would have no idea how to do that, but anything that makes this a set and forget in the spirit of having this run unattended on a server would be a bonus obviously.

First, that is far outside the scope of what this whole project does and, unless it could issue docker run commands to the Server, it wouldn't work anyway, which leads me to my next point.

Second, this container cannot be added to the CA repository as it is not designed as a permanently running container. You run it with the docker run command and the specified parameters when you want to scrape a MediaWiki instance and that's it. It does not constantly run on a Docker system for you to use it when you want to.

**Comment by GlassedSilver** [comment]
Thanks for the clarification! I guess what I'd be more looking for to begin with is a front-end first and then possibly request that instead of the backend-only solution.

I guess the CA for ClamAV led me a bit to believe that this could be implemented in a similar style. However if it's even more manual than that then I guess there's nothing left to look at. :)

Cheers!
