### ISSUE TITLE
xbackbone requires PHP_UPLOAD_MAX_FILESIZE to be defined or it won't launch

### ISSUE THREAD

**Issue by suckerfish** [selfhosters/unRAID-CA-templates#110]
Error in logs: "-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
/opt/docker/provision/entrypoint.d/01-app.sh: line 3: PHP_UPLOAD_MAX_FILESIZE: unbound variable"

If you add a variable for it manually and define it, it works fine.

**Comment by jrdnlc** [comment]
I'll fix it. Thanks
