### ISSUE TITLE
CA Template Request - tesla_dashcam

### ISSUE THREAD

**Issue by porterpath** [selfhosters/unRAID-CA-templates#115]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/magicalyak/tesla_dashcam/
https://github.com/magicalyak/tesla_dashcam
https://github.com/ehendrix23/tesla_dashcam

#### Post any additional information about the project that you know is important
 
`<?xml version="1.0"?>
<Container version="2">
  <Name>tesla_dashcam</Name>
  <Repository>magicalyak/tesla_dashcam</Repository>
  <Registry>https://hub.docker.com/r/magicalyak/tesla_dashcam/</Registry>
  <Network>bridge</Network>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://hub.docker.com/r/magicalyak/tesla_dashcam/</Support>
  <Project/>
  <Overview>Docker image for processing Tesla Dashcam videos using ehendrix23/tesla_dashcam github project</Overview>
  <Category/>
  <WebUI/>
  <Icon>https://github.com/ehendrix23/tesla_dashcam/blob/dev/tesla_dashcam/tesla_dashcam.png?raw=true</Icon>
  <Description>Docker image for processing Tesla Dashcam videos using ehendrix23/tesla_dashcam github project</Description>
  <Config Name="Key 1" Target="/Movies" Default="" Mode="rw" Description="Container Path: /Movies" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/Videos/</Config>
  <Config Name="Key 2" Target="/Volumes/CAM/TeslaCam" Default="" Mode="rw" Description="Container Path: /Volumes/CAM/TeslaCam" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/TeslaCam/</Config>
  <Config Name="Key 3" Target="/root/Import" Default="" Mode="rw" Description="Container Path: /root/Import" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/TeslaCam/</Config>
  <Config Name="Key 4" Target="/root/Videos" Default="" Mode="rw" Description="Container Path: /root/Videos" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/Videos/</Config>
  <Config Name="WORKDIR" Target="/usr/src/app/tesla_dashcam" Default="" Mode="rw" Description="Container Path: /usr/src/app/tesla_dashcam" Type="Path" Display="always" Required="false" Mask="false"/>
</Container>`

I am guessing at what configs I needed.  But as is, It'll run. 
log > Monitoring for TeslaCam Drive to be inserted. Press CTRL-C to stop

But If I thought it needs a folder, so I populated "WORKDIR" Target="/usr/src/app/tesla_dashcam" Default=""
with a folder  e.g. appdata/tesla_dashcam , but now it doesn't start.
log > python3: can't open file 'tesla_dashcam/tesla_dashcam.py': [Errno 2] No such file or directory

**Comment by jrdnlc** [comment]
It's working for me. `Monitoring for TeslaCam Drive to be inserted. Press CTRL-C to stop`
Now time to grab some footage off the flash drive :D

**Comment by jrdnlc** [comment]
All you need is the `/import`and `/movies ` volume. If you want to customize the videos add your custom values under `Post Arguments` in the template.

**Comment by porterpath** [comment]
thank you, that makes sense

**Comment by porterpath** [comment]
`<?xml version="1.0"?>
<Container version="2">
  <Name>tesla_dashcam</Name>
  <Repository>magicalyak/tesla_dashcam</Repository>
  <Registry>https://hub.docker.com/r/magicalyak/tesla_dashcam/</Registry>
  <Network>bridge</Network>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://hub.docker.com/r/magicalyak/tesla_dashcam/</Support>
  <Overview>Docker image for processing Tesla Dashcam videos using ehendrix23/tesla_dashcam github project </Overview>
  <Category>Tools: MediaApp:Video</Category>
  <Icon>https://github.com/ehendrix23/tesla_dashcam/blob/dev/tesla_dashcam/tesla_dashcam.png?raw=true</Icon>
  <ExtraParams>--runtime=nvidia</ExtraParams>
  <PostArgs>--skip_existing --delete_source --monitor_trigger ARCHIVE_UPLOADED --layout DIAMOND --halign RIGHT --valign BOTTOM --fontcolor white --motion_only --merge --gpu --gpu_type nvidia --quality LOW --compression slower --encoding x265</PostArgs>
  <Description>Docker image for processing Tesla Dashcam videos using ehendrix23/tesla_dashcam github project </Description>
  <Config Name="Key 1" Target="/Movies" Default="" Mode="rw" Description="Container Path: /Movies" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/Videos/</Config>
  <Config Name="Key 2" Target="/Volumes/CAM/TeslaCam" Default="" Mode="rw" Description="Container Path: /Volumes/CAM/TeslaCam" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/TeslaCam/</Config>
  <Config Name="Key 3" Target="/root/Import" Default="" Mode="rw" Description="Container Path: /root/Import" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/TeslaCam/</Config>
  <Config Name="Key 4" Target="/root/Videos" Default="" Mode="rw" Description="Container Path: /root/Videos" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/tesla/Videos/</Config>
  <Config Name="Nvidia Key 1" Target="NVIDIA_DRIVER_CAPABILITIES" Default="all" Mode="" Description="Container Variable: NVIDIA_DRIVER_CAPABILITIES" Type="Variable" Display="always" Required="false" Mask="false">all</Config>
  <Config Name="Nvidia Key 2" Target="NVIDIA_VISIBLE_DEVICES" Default="GPU-### from nvidia plugin" Mode="" Description="Container Variable: NVIDIA_VISIBLE_DEVICES" Type="Variable" Display="always" Required="false" Mask="false">GPU-486af9bf-e2dc-2e82-7082-eae2454b205e</Config>
</Container>`


output log:
GPU acceleration is enabled
Monitoring for trigger ARCHIVE_UPLOADED to exist. Press CTRL-C to stop

Thank you, now time to test.

**Comment by timtong1982** [comment]
knock knock, is this guy merged?
