### ISSUE TITLE
CA Template Request - Crushftp9

### ISSUE THREAD

**Issue by mikeylikesrocks** [selfhosters/unRAID-CA-templates#117]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**

Dockerhub Repo
https://registry.hub.docker.com/repository/docker/mdschaefer/crushftp9

Github Repo
https://github.com/mikeylikesrocks/unRAID-crushftp9

Unraid Template
https://github.com/mikeylikesrocks/unraid-docker-templates/blob/master/crushftp9.xml

#### Post any additional information about the project that you know is important 

There is already a Crushftp image in CA but it is for ver 8 of Crushftp.  This image is for ver 9 and has some updates to allow more functionality there weren't possible in the other image due to its base image.

**Comment by jrdnlc** [comment]
I’ll go ahead and add this. Thanks
