### ISSUE TITLE
CA Template Request - Owntracks/Recorder

### ISSUE THREAD

**Issue by bdydrp** [selfhosters/unRAID-CA-templates#124]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/owntracks/docker-recorder/
https://hub.docker.com/r/owntracks/recorder

#### Post any additional information about the project that you know is important 
Also has a front end UI, dont know if you need both
https://github.com/owntracks/frontend

**Comment by Roxedus** [comment]
Looks to have more setup than we can test easily. You can give it a shot yourself using the guide linked in the issue.
