### ISSUE TITLE
CA Template Request - XBackBone

### ISSUE THREAD

**Issue by nameproof** [selfhosters/unRAID-CA-templates#14]
**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/Pe46dro/XBackBone-docker
https://hub.docker.com/r/pe46dro/xbackbone-docker

**Comment by gilbN** [comment]
https://github.com/selfhosters/unRAID-CA-templates/commit/93eb0862a3f16d40e865621050918bf4e3ddf10d fixed

**Comment by nameproof** [comment]
Cheers man
