### ISSUE TITLE
CA Template Request - Wallabag

### ISSUE THREAD

**Issue by abb0r** [selfhosters/unRAID-CA-templates#140]
**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/wallabag/wallabag
https://hub.docker.com/r/wallabag/wallabag

#### Post any additional information about the project that you know is important 
It's a selfhosted alternative to Pocket.

**Comment by TerrierX** [comment]
It already exists in unraid as a template if you search in the community apps:
![image](https://user-images.githubusercontent.com/62567463/81408969-84309e00-913e-11ea-9962-e4447c194746.png)

https://github.com/A75G/docker-templates/blob/master/README.md#wallabag

**Comment by christronyxyocum** [comment]
Closing per the above comment showing it already exists.
