### ISSUE TITLE
CA Template Request - Deemix

### ISSUE THREAD

**Issue by abb0r** [selfhosters/unRAID-CA-templates#141]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
Git: https://notabug.org/RemixDev/deemix
Docker: https://hub.docker.com/r/bocki/deemix

#### Post any additional information about the project that you know is important 
DeezloaderRemix is discontinued, this is the replacement by the same developer. It is in development, but should work fine.

**Comment by gilbN** [comment]
https://github.com/selfhosters/unRAID-CA-templates/pull/146
