### ISSUE TITLE
CA Template Request - BabyBuddy

### ISSUE THREAD

**Issue by noja11** [selfhosters/unRAID-CA-templates#145]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/babybuddy/babybuddy
https://hub.docker.com/r/babybuddy/babybuddy

#### Post any additional information about the project that you know is important 
It depends on a postgres11 database, but I can't get them to connect together in unRAID.  Thank you all so much for any consideration!

**Comment by gilbN** [comment]
You will need to run this with compose. Looks like database host is hardcoded to `db`, you could perhaps rename the postgres container to `db` and use custom docker network.

https://github.com/babybuddy/babybuddy/blob/e2f432f92cfe13f63b2e179f3607a2158cb9f2c9/babybuddy/settings/docker.py#L13
