### ISSUE TITLE
CA Template Request - LG Connector

### ISSUE THREAD

**Issue by sbukiet** [selfhosters/unRAID-CA-templates#150]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/fison67/lg-connector

https://github.com/fison67/LG-Connector#prerequisites

#### Post any additional information about the project that you know is important 
<info here>

**Comment by gilbN** [comment]
Added in https://github.com/selfhosters/unRAID-CA-templates/pull/149

**Comment by sbukiet** [comment]
Possible to add the LG Connector BETA version as well?

https://hub.docker.com/layers/fison67/lg-connector/beta/images/sha256-172e9588302a0587094834d48ac497f4eddafa3c10755ef287eafedaa858daaf?context=explore

**Comment by gilbN** [comment]
Just add the tag yourself

**Comment by sbukiet** [comment]
Possible to explain how to do that? Very new to all this.

**Comment by gilbN** [comment]
![20DA3DFD-471A-4256-BFA9-6F35386907DC](https://user-images.githubusercontent.com/24592972/87561745-62fba900-c6bd-11ea-901b-26a15ceac1c6.jpeg)
Like so

**Comment by sbukiet** [comment]
Amazing, thanks
