### ISSUE TITLE
CA Template Request - Elastiflow

### ISSUE THREAD

**Issue by slothtechtv** [selfhosters/unRAID-CA-templates#152]
Elastiflow docker container request.

**Please add the dockerhub repo link and github/gitlab link below**

https://hub.docker.com/r/robcowart/elastiflow-logstash-oss
https://github.com/robcowart/elastiflow

#### Post any additional information about the project that you know is important 
<info here>

**Comment by Roxedus** [comment]
This also rely on kibana, which there currently isnt a template for (and I wont make one, due to the complexity of the whole stack), and if one got that to run, this shouldnt be a problem either.
