### ISSUE TITLE
CA Template Request - Authelia

### ISSUE THREAD

**Issue by strongy** [selfhosters/unRAID-CA-templates#161]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/authelia/authelia
https://hub.docker.com/r/authelia/authelia

#### Post any additional information about the project that you know is important 
<info here>

**Comment by Roxedus** [comment]
Already in CA
