### ISSUE TITLE
CA Template Request - DeepStack

### ISSUE THREAD

**Issue by xsinmyeyes** [selfhosters/unRAID-CA-templates#164]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/deepquestai/deepstack

#### Post any additional information about the project that you know is important 
https://deepstack.cc/support/installation/docker
CPU Version

**Comment by Roxedus** [comment]
Im not comfortable with adding software that requires you to have user in order to read the documentation. I will leave it open, and hope their open-source offering changes that when it comes.
