### ISSUE TITLE
CA Template Request - Confluence

### ISSUE THREAD

**Issue by bigmak40** [selfhosters/unRAID-CA-templates#167]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/atlassian/confluence-server
No github/gitlab links available

**Post any additional information about the project that you know is important**
Here's a link to the Atlassian documentation on how it should be done. I'm just confused on how to get it with two separate locations (confluence and synchrony).
https://confluence.atlassian.com/doc/running-confluence-behind-nginx-with-ssl-858772080.html

**Comment by gilbN** [comment]
![image](https://user-images.githubusercontent.com/24592972/88487808-a17c4800-cf88-11ea-9133-a48ae986fe3a.png)
Whats wrong with the one that's already there?

**Comment by bigmak40** [comment]
Ok I'm dumb, it is in there already. Closing this issue, sorry.
