### ISSUE TITLE
CA Template Request - pihole-updatelists

### ISSUE THREAD

**Issue by TadMSTR** [selfhosters/unRAID-CA-templates#172]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/jacklul/pihole
https://github.com/jacklul/pihole-updatelists

#### Post any additional information about the project that you know is important 
<info here>

**Comment by Roxedus** [comment]
The template would be the same as the pihole template, pluss adding `/etc/pihole-updatelists/` as a volume, and setting the repo to `jacklul/pihole`
