### ISSUE TITLE
CA Template Request - Zwave2MQTT

### ISSUE THREAD

**Issue by jaburges** [selfhosters/unRAID-CA-templates#173]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)
***

**Please add the dockerhub repo link and github/gitlab link below**
[Dockerhub](https://hub.docker.com/r/robertslando/zwave2mqtt)
[Github](https://github.com/OpenZWave/Zwave2Mqtt)

#### Post any additional information about the project that you know is important 
Typical docker command:
```
docker run --rm -it -p 8091:8091 --device=/dev/ttyACM0 -v /path/to/folder:/usr/src/app/store robertslando/zwave2mqtt:latest
```
I've asked the dev if its possible to pass the z-wave `network key` as a variable as would be useful for first setup.
Not entirely sure what else is needed, but happy to help gather more information :)
(this would make updating much easier too it seems)

**Comment by Roxedus** [comment]
Is cloning a repository to the appdata really necessary?
Ref https://github.com/OpenZWave/Zwave2Mqtt/issues/620#issuecomment-678461470

**Comment by jaburges** [comment]
no i believe it builds itself the first time now (but when it was first built i believe it needed it)

**Comment by Roxedus** [comment]
Will be merged in a few hours

**Comment by robertsLando** [comment]
> I've asked the dev if its possible to pass the z-wave network key as a variable as would be useful for first setup.

@jaburges Done!

**Comment by Roxedus** [comment]
Nice, will be active on the next merge to master

**Comment by robertsLando** [comment]
Already merged

**Comment by Roxedus** [comment]
Yes, but not on our side 😉

**Comment by jaburges** [comment]
tested and working 
(note I used the host path as before so would pick up a lot of my settings already - i've not tested on a fresh install)
