### ISSUE TITLE
CA Template Request - JIRA

### ISSUE THREAD

**Issue by roweyourboat90** [selfhosters/unRAID-CA-templates#174]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/atlassian/jira-software/

#### Post any additional information about the project that you know is important 
<info here>

**Comment by Roxedus** [comment]
To specify, you want JIRA Software, the all on one kind of deal?
