### ISSUE TITLE
CA Template Request - SSTVProxy

### ISSUE THREAD

**Issue by itskamel** [selfhosters/unRAID-CA-templates#175]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
<https://hub.docker.com/r/stokkes/sstvproxy/

#### Post any additional information about the project that you know is important 
This is a proxy for Smooth Streams IPTV

**Comment by gilbN** [comment]
@itskamel template is ready for testing in https://github.com/selfhosters/unRAID-CA-templates/tree/testing/templates
Add it to your template repositories.
![image](https://user-images.githubusercontent.com/24592972/92640633-df85bf00-f2dd-11ea-9b0a-61e6559a5816.png)

Let us know if it works.
