### ISSUE TITLE
CA Template Request - Paperless

### ISSUE THREAD

**Issue by ark-** [selfhosters/unRAID-CA-templates#18]
**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/danielquinn/paperless/

#### Post any additional information about the project that you know is important 
Seems to want to run in 2 separate docker containers a webserver and a consumer. 

Here are the official docs:
https://paperless.readthedocs.io/en/latest/setup.html#setup-installation-docker

Here is a thread in the unraid forums on someone managing to get it to work.
https://forums.unraid.net/topic/71733-help-with-paperless-dockerhub-unraid/

Thanks in advance guys. Doing great work here! 😁

**Comment by gilbN** [comment]
added
