### ISSUE TITLE
CA Template Request - Seedsync

### ISSUE THREAD

**Issue by cferra** [selfhosters/unRAID-CA-templates#187]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/ipsingh06/seedsync
https://github.com/ipsingh06/seedsync

#### Post any additional information about the project that you know is important 
would  need a webui port, as well as some lines for sync folder paths.

**Comment by jrdnlc** [comment]
Sorry for delay. This is done #202
