### ISSUE TITLE
CA Template Request - paperless-ng

### ISSUE THREAD

**Issue by Tooa** [selfhosters/unRAID-CA-templates#189]
## Paperless-ng - a (beautiful) paperless fork

* Github: https://github.com/jonaswinkler/paperless-ng
* Docker Hub: jonaswinkler/paperless-ng
* Documentation: https://paperless-ng.readthedocs.io/en/latest/
* Migration from paperless to paperless-ng: https://paperless-ng.readthedocs.io/en/latest/setup.html?highlight=migration#migration-to-paperless-ng

Paperless-ng is a well-maintained fork of [paperless](https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/paperless.xml). Unfortunately, the later hasn't received a lot of updates and bug fixes in the past. Even pull requests are not merged for some time now. Thus, I propose to add paperless-ng as **additional** alternative to paperless and papermerge to the Unraid CA. 

Here are a few key features of paperless-ng:

* New front end build with Angular. It features full text search with scored and highlighted results, savable filters, a dashboard, and document uploading on the landing page.
* Mobile support is also almost there. Some layouts don't work yet on small screens.
* New mail consumer that supports multiple accounts and custom filters and actions. Fully tested!
* Paperless-ng trains a neural network on your documents and assigns tags and corerspondents automatically, if you instruct it to do so.
* Updated dependencies.
* More tests of critical backend parts.
* A proper task processing queue that can consume multiple documents in parallel. Consumption of many documents is now blazing fast on multi core system. Fixed much of the consumer code, so that it does not block the database during consumption, for instance.
* Compatible with the paperless iOS and Android [app](https://github.com/bauerj/paperless_app)

Paperless-ng supports SQlite and PostgresQL as database. I suggest to stick with SQlite as the default configuration. Paperless-ng is available as pre-release right now. So, we might want to flag the template with beta in its name.

What do you guys think about paperless-ng?

Read [here](https://github.com/the-paperless-project/paperless/issues/711) for more information about the difference between paperless and paperless-ng.

**Comment by Tooa** [comment]
This issue is resolved with #190. I wonder, if we should reach out to the guys over at LinuxServer.io and ask whether they are interested in creating a multi-architecture docker image for `paperless-ng`. Then people could install `paperless-ng` also on their Raspberry Pi.

**Comment by Roxedus** [comment]
Just keep your eyes open 😉
