### ISSUE TITLE
CA Template Request - Xibo

### ISSUE THREAD

**Issue by karldonteljames** [selfhosters/unRAID-CA-templates#19]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/xibosignage/xibo-cms
https://github.com/xibosignage/xibo-docker

#### Post any additional information about the project that you know is important 
I tried to install this from dockerhub, but it had no webui, I assume I did something wrong. Many Thanks.

**Comment by gilbN** [comment]
added
