### ISSUE TITLE
CA Template Request - twonkyserver

### ISSUE THREAD

**Issue by fritolays** [selfhosters/unRAID-CA-templates#194]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/dtjs48jkt/twonkyserver
https://github.com/H2CK/twonkyserver

#### Post any additional information about the project that you know is important 
A note saying that a valid licence is needed to run this docker?

**Comment by jrdnlc** [comment]
Will talk it out with the team about adding this app due to license requirement. I already have it running so if the team agrees i'll submit the template. Closing this for now

**Comment by Roxedus** [comment]
We can use the License tag for that. It takes a arbitrary string. https://forums.unraid.net/topic/38619-docker-template-xml-schema/
