### ISSUE TITLE
CA Template Request - Shinobi (NVR)

### ISSUE THREAD

**Issue by TheMrRandomDude** [selfhosters/unRAID-CA-templates#195]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/shinobicctv/shinobi/
https://gitlab.com/Shinobi-Systems/Shinobi/-/tree/dev/Docker

#### Post any additional information about the project that you know is important 
It's very documented and an easy install. I tried to make it running myself, but I didn't have much luck. There are already two existing CA templates, and one is even Spaceinvader. The problem is they both are using private containers which don't recieve updates and aren't developed, and both of them have bugs with SQL today, and are impossible to use without major issues.

I believe it would be a great solution to use the official shinobicctv/shinobi repo instead.

Thanks :) Shouldn't be a hard template to make, as there are already two existing ones, it's open source and there's a ton of documentation.

**Comment by jaburges** [comment]
@TheMrRandomDude I had a crack at creating the template - it should be in testing now
