### ISSUE TITLE
CA Template Request - TeslaMate

### ISSUE THREAD

**Issue by discojon** [selfhosters/unRAID-CA-templates#196]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/adriankumpf/teslamate

#### Post any additional information about the project that you know is important 
I'm currently running this in a lightweight linux VM. It would be amazing to have it as a dockerfile in CA

**Comment by Roxedus** [comment]
This is not really easy to put into a template. It depends on a few other containers, including their own release of Grafana. This setup really should be done with compose.
