### ISSUE TITLE
CA Template Request - Mylar3

### ISSUE THREAD

**Issue by KFlipDev** [selfhosters/unRAID-CA-templates#197]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
Dockerhub: https://hub.docker.com/r/linuxserver/mylar3
Github: https://github.com/linuxserver/docker-mylar3

#### Post any additional information about the project that you know is important 
I don't know enough. Just hoping to see a Mylar3 community app on unraid!

**Comment by jrdnlc** [comment]
It's already in CA. 
<img width="494" alt="Screen Shot 2020-12-29 at 9 54 04 PM" src="https://user-images.githubusercontent.com/15741144/103332810-6642e100-4a20-11eb-847c-24f054759ef5.png">

**Comment by Roxedus** [comment]
Linuxserver will handle this themselves. https://github.com/linuxserver/docker-templates/pull/224
