### ISSUE TITLE
CA Template Request - Kemono2 aka Kemonoparty 2

### ISSUE THREAD

**Issue by GlassedSilver** [selfhosters/unRAID-CA-templates#200]
**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/openyiff/kemonoparty
https://github.com/OpenYiff/Kemono2/

#### Post any additional information about the project that you know is important 
Looked into making this one myself at least to try out, but didn't really understand how to go about this one specifically.
Seems like it's multi-pieced? (more than one container, but one docker template file?)

**Comment by jrdnlc** [comment]
This won't be added for obvious reasons.
