### ISSUE TITLE
CA Template Request - Seedsync

### ISSUE THREAD

**Issue by jkexbx** [selfhosters/unRAID-CA-templates#201]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/ipsingh06/seedsync
https://hub.docker.com/r/ipsingh06/seedsync

#### Post any additional information about the project that you know is important 
https://github.com/ipsingh06/seedsync/issues/25#issuecomment-466546009
The settings posted work to set it up manually. The WebUI should be http://192.168.0.4:8800/dashboard

**Comment by jrdnlc** [comment]
Duplicate #187. Closing this
