### ISSUE TITLE
CA Template Request - Plausible Analytics

### ISSUE THREAD

**Issue by oliverjhyde** [selfhosters/unRAID-CA-templates#206]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/plausible/analytics/
https://github.com/plausible/analytics

#### Post any additional information about the project that you know is important 
Requires postgresql & Clickhouse (separate issue created for Clickhouse server)
Docker-compose guide [here](https://cyberhost.uk/selfhost-plausible-analytics/).

**Comment by oliverjhyde** [comment]
Some extra information [here ](https://github.com/plausible/hosting) about selfhosting this

**Comment by jrdnlc** [comment]
Not an easy template to create since it depends on a few other containers. Should be setup with compose instead. #207
