### ISSUE TITLE
CA Template Request - Clickhouse Server

### ISSUE THREAD

**Issue by oliverjhyde** [selfhosters/unRAID-CA-templates#207]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/yandex/clickhouse-server
https://github.com/ClickHouse/ClickHouse

#### Post any additional information about the project that you know is important 
Container exposes 8123 port for HTTP interface and 9000 port for native client.

**Comment by jrdnlc** [comment]
#206
