### ISSUE TITLE
CA Template Request - navidrome

### ISSUE THREAD

**Issue by bradtn** [selfhosters/unRAID-CA-templates#209]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/deluan/navidrome

https://github.com/deluan/navidrome

#### Post any additional information about the project that you know is important 
<info here>

**Comment by bradtn** [comment]
Thanks for the work and time for doing this whoever might do it, much appreciated

**Comment by jrdnlc** [comment]
I'll submit this later today. So far it's running fine - will do more testing.

**Comment by bradtn** [comment]
> I'll submit this later today. So far it's running fine - will do more testing. 

Wow thanks!
