### ISSUE TITLE
CA Template Request - Yomiko

### ISSUE THREAD

**Issue by GlassedSilver** [selfhosters/unRAID-CA-templates#218]
**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/kyubi/yomiko/
https://github.com/KyubiSystems/Yomiko

#### Post any additional information about the project that you know is important 
Nothing really important I'd know of.

**Comment by Roxedus** [comment]
There is no instructions for this image. Feel free to reopen once that changes.
