### ISSUE TITLE
CA Template Request - Akaunting

### ISSUE THREAD

**Issue by mikedemon** [selfhosters/unRAID-CA-templates#222]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/akaunting/docker
https://hub.docker.com/r/akaunting/akaunting

#### Post any additional information about the project that you know is important 
In the github readme, they talk about copying and modifying a .env file, but i'm afraid i don't fully understand how to work with said file in UnRAID. Any help or guidance is greatly appreciated.

Thank you

**Comment by bradtn** [comment]
Following

**Comment by tronyx** [comment]
Whoops, sorry about that, I didn't mean to delete the comment.

**Comment by GilbN** [comment]
Exists in CA
