### ISSUE TITLE
CA Template Request - MonitoRSS

### ISSUE THREAD

**Issue by jaazyfofo** [selfhosters/unRAID-CA-templates#227]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
[Dockerhub](https://hub.docker.com/r/synzen/monitorss)
[Github](https://github.com/synzen/MonitoRSS)

#### Post any additional information about the project that you know is important 

---

Thank you in advance for your help.

**Comment by Roxedus** [comment]
I presume you want both the webui and the bot?

**Comment by jaazyfofo** [comment]
Hello.

Yes, if it's possible, I would like to. Thank you in advance !

**Comment by jaazyfofo** [comment]
Thank you very much for your help @Roxedus. This template will help me a lot :)

**Comment by Repooc** [comment]
> Thank you very much for your help Roxedus. This template will help me a lot :)

@jaazyfofo If you were able to get this behind a reverse proxy, I would love some input as for some reason, I'm having issues with it.

**Comment by Roxedus** [comment]
With SWAG you can just copy the _template, and alter the upstream_ parts.

**Comment by Repooc** [comment]
Yeah, I did that... i have swag setup with cloudflare with wildcard and i even added a cname just like other subdomains i use and its still trying to show what use to be the default nginx index page... i changed a syncthing.subdomain.conf to the ip:port of the web interface and it shows but setting up another domain, its acting like it doesnt want to work.
