### ISSUE TITLE
CA Template Request - Visual Subnet Calculator

### ISSUE THREAD

**Issue by mwheelz** [selfhosters/unRAID-CA-templates#230]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/davidc/subnets

#### Post any additional information about the project that you know is important 
Needs ports 5001:80 open

**Comment by Roxedus** [comment]
Doesnt seem like davidc offers a prebuilt container for it on dockerhub. I am hesitant to add the one I did found
