### ISSUE TITLE
CA Template Request - NordVPN

### ISSUE THREAD

**Issue by benfishbus** [selfhosters/unRAID-CA-templates#237]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/bubuntux/nordvpn/
https://github.com/bubuntux/nordvpn

#### Post any additional information about the project that you know is important 
This seems to be the only VPN container that supports NordLynx (NordVPN's implementation of WireGuard).

Icon suggestion:   https://s1.nordcdn.com/nordvpn/media/1.752.0/images/global/favicon/favicon-196x196.png
Extra Parameters required:   --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctl net.ipv4.conf.all.rp_filter=2
Device required:   /dev/net/tun

Whatever application container you want to run through this needs the following Extra Parameter defined:  --net=container:nordvpn

**Comment by GilbN** [comment]
Make a PR and Ill merge.
