### ISSUE TITLE
CA Template Request - Technitium DNS

### ISSUE THREAD

**Issue by cbackas** [selfhosters/unRAID-CA-templates#24]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/doko89/technitium
https://github.com/TechnitiumSoftware/DnsServer

**Comment by Roxedus** [comment]
Thanks for this suggestion, however i don't feel like adding a container without being able to look at the dockerfile. The one you linked is also very old, it is six months behind the latest commit for the project. I will leave this open though, maybe i will make a container myself for the project.

**Comment by cbackas** [comment]
Yeah I figured that might be the case... I thought about making a container myself to pass to you but idk how to do that... I manually got the dockerhub version of the container running on my server so i can play with it to see if its something I'd like to invest my time in anyway. 

Thanks

**Comment by Roxedus** [comment]
I have made a container for it. going to play with it for a few days to iron out the bugs.

**Comment by cbackas** [comment]
> 
> 
> I have made a container for it. going to play with it for a few days to iron out the bugs.

So far so good? Any testing I could do? Excited to potentially use a more updated version of Technitium

**Comment by Roxedus** [comment]
https://github.com/Roxedus/docker-TS-DnsServer

no template yet
