### ISSUE TITLE
CA Template Request - MatterBridge

### ISSUE THREAD

**Issue by ciroiriarte** [selfhosters/unRAID-CA-templates#245]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/42wim/matterbridge
https://matrix.org/docs/projects/bot/matterbridge
https://hub.docker.com/r/42wim/matterbridge/

#### Post any additional information about the project that you know is important 
It's a companion to Mattermost chat solution, it can be deployed as standalone to bridge/connect different chat platforms.

**Comment by Roxedus** [comment]
I don't really see this fitting in CA. It is easy to set up yourself, it only needs a path. It also doesn't have a UI so I can see it causing some confusion.
