### ISSUE TITLE
CA Template Request - spotifeed

### ISSUE THREAD

**Issue by mattdgren** [selfhosters/unRAID-CA-templates#247]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/danielbrierton/spotifeed/

#### Post any additional information about the project that you know is important 
https://github.com/timdorr/spotifeed/issues/7
Live demo: https://spotifeed.timdorr.com/

**Comment by Roxedus** [comment]
There need to be a image existing, cant work with just a dockerfile
