### ISSUE TITLE
unRAID-CA-templates/templates/protonmail-bridge.xml - Instructions incorrect

### ISSUE THREAD

**Issue by Jawbone220** [selfhosters/unRAID-CA-templates#271]
Following the instructions listed on the template do not work in successfully setting up protonmail-bridge. 

Snags I ran into:

1. the line `/entrypoint.sh init` does not work and should include a preceding period `./entrypoint.sh init`  ->Submitted   PR #269   

2.  
-Listed Instructions: "Wait for the bridge to startup, use `login` command and follow the instructions to add your account into the bridge. Then use  `info` to see the configuration information (username and password). After that, use `exit` to exit the bridge."

-Expected behavior: bridge starts and logs into console, where `login` prompts user to add credentials.

-Actual behavior: bridge starts, but does not dump the user into the protonmail-bridge cli as it should. This issue is also known over in the docker container git referenced [https://github.com/shenxn/protonmail-bridge-docker/issues/4#issuecomment-815088607](url) ; Additionally, console will stay in bash and will not open `protonmail-bridge --cli` however the `login` command will still populate with user and password, but return an "incorrect login" info.

-Resolution/workaround: Running the `./entrypoint.sh init` command, Running `top` and then killing duplicate protonmail-bridge process, (both are killed in system). Then running command `protonmail-bridge --cli` will successfully load into the protonmail bridge console which allows the user to run `login` and add account. After successfully adding account and restarting container, container then behaves normally and will work as expected.  

Did not submit PR for issue 2, as I am unsure if anything can be done to mitigate some of these steps for the end-user.

**Comment by Roxedus** [comment]
We cannot solve 2. with templates, as the console button is either sh or bash, you can however add your workaround in the description in your PR
