### ISSUE TITLE
CA Template Request - Twint

### ISSUE THREAD

**Issue by futureb0und** [selfhosters/unRAID-CA-templates#276]
**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/twintproject/twint
https://github.com/twintproject/twint-docker
https://hub.docker.com/r/thetwintproject/twint

#### Post any additional information about the project that you know is important 
Twint is an advanced Twitter scraping tool written in Python that allows for scraping Tweets from Twitter profiles without using Twitter's API.

**Comment by bravohotel91** [comment]
This project is no longer active. Can we close this issue @futureb0und ?
