### ISSUE TITLE
CA Template Request - ripme

### ISSUE THREAD

**Issue by b883452345** [selfhosters/unRAID-CA-templates#285]
Please add a template for ripme

https://github.com/RipMeApp/ripme
https://github.com/RipMeApp/ripme-docker
https://hub.docker.com/r/crunklydunks/ripme

**Comment by bravohotel91** [comment]
This project seems to have ceased development. Can we move to close this issue?

**Comment by bravohotel91** [comment]
Nvm. Found a project that furthered the original efforts: https://github.com/ripmeapp2/ripme
