### ISSUE TITLE
CA Template Request - <double-take>

### ISSUE THREAD

**Issue by kierran0094** [selfhosters/unRAID-CA-templates#296]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/jakowenko/double-take
https://github.com/jakowenko/double-take

#### Post any additional information about the project that you know is important 
https://github.com/corgan2222/unraid-templates/tree/main/double-take

**Comment by GilbN** [comment]
Already exist in CA.
