### ISSUE TITLE
CA Template Request - WebODM - OpenDroneMap

### ISSUE THREAD

**Issue by TheMrRandomDude** [selfhosters/unRAID-CA-templates#30]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/opendronemap/webodm_webapp/
https://github.com/OpenDroneMap/WebODM

#### Post any additional information about the project that you know is important 
It's a very powerful open source software for creating 3D models with drones and Gopro cameras. It's very easy to deploy with just a few commands in Docker on Windows.

The 3D modeling industry is currently filled with very expensive ($200+) software solutions for modeling, and this open source project is a solution to it!

It's pretty neat! Check it out please :)

**Comment by TheMrRandomDude** [comment]
I apologize for double posting, just wanted to add this guide as well I found in documentation:

https://docs.opendronemap.org/installation.html#linux

I succesfully got it running on Linux this way, however I was unsure how to pack it all in Docker. I tried but failed unfortuantely.

**Comment by gilbN** [comment]
I had a look at this again. Quite complicated setup. Looks like you need redis, postgres, webodm db image and then the webodm webapp image. I think you're better off using compose to get this setup on unraid. https://github.com/OpenDroneMap/WebODM/blob/master/docker-compose.yml

**Comment by TheMrRandomDude** [comment]
The best way to go is indeed compose. It's far too complex to be used with standard docker. I'm closing this and marking it as complete, the best solution is compose, 100%.
