### ISSUE TITLE
CA Template Request - GoAccess

### ISSUE THREAD

**Issue by masterwishx** [selfhosters/unRAID-CA-templates#306]
Goaccess that we have in CA template is old version from https://hub.docker.com/r/gregyankovoy/goaccess/dockerfile
updated year ago

Official is:
https://hub.docker.com/r/allinurl/goaccess
(https://github.com/allinurl/goaccess)

#### Post any additional information about the project that you know is important 
About
GoAccess is a real-time web log analyzer and interactive viewer that runs in a terminal in *nix systems or through your browser.

**Comment by lordraiden** [comment]
I would be very interested on this as well
