### ISSUE TITLE
CA Template Request - <homeseer-4>

### ISSUE THREAD

**Issue by vonnaone** [selfhosters/unRAID-CA-templates#318]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/vonnaone/homeseer-4

#### Post any additional information about the project that you know is important 
I can't seem to publish this to docker hub but can create a docker image on github.  would love to see it published, just not sure how to get it up on docker hub.

Thanks

**Comment by bravohotel91** [comment]
This project has not been updated in over 2 years. Would we be okay to close this issue?

**Comment by nwithan8** [comment]
@vonnaone It seems your container is locked to always download Homeseer v4.2.8.0. Looking at the Homeseer website, their latest version is v4.2.19.5.

If we were to make an Unraid template for a Dockerized version of Homeseer, we would want to use a Docker image that is either manually updated to or automatically downloads the latest Homeseer binary inside the container (preferably manually so users could control which Homeseer version they are running).

For now, we are going to close this ticket as the provided Docker image is unsuitable for an Unraid template.
