### ISSUE TITLE
CA Template Request - mycroft ai

### ISSUE THREAD

**Issue by thorin29** [selfhosters/unRAID-CA-templates#330]
**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/mycroftai/docker-mycroft/
https://github.com/MycroftAI/docker-mycroft

#### Post any additional information about the project that you know is important 
Mycroft is an open source virtual assistant AI with many integrations (e.g. Home Assistant), and skills. There is a GUI: https://github.com/MycroftAi/Mycroft-GUI

**Comment by bravohotel91** [comment]
This project has been abandoned as of 2023. Can we close this issue?

**Comment by nwithan8** [comment]
Mycroft is (unfortunately) no longer actively developed:
https://mycroft.ai/blog/update-from-the-ceo-part-1/

Bummer, I almost invested in them at the very beginning.

Since the project is no longer maintained, we will not be supporting an Unraid template for this.

**Comment by thorin29** [comment]
So in the past 2 years Open Voice OS has taken over Mycroft. 

https://github.com/OpenVoiceOS/ovos-docker

**Comment by nwithan8** [comment]
> So in the past 2 years Open Voice OS has taken over Mycroft. 
> 
> https://github.com/OpenVoiceOS/ovos-docker

Please open a new template request issue with details about OVOS.
