### ISSUE TITLE
CA Template Request - Personal Management System

### ISSUE THREAD

**Issue by formless63** [selfhosters/unRAID-CA-templates#333]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/Volmarg/personal-management-system/tree/docker
https://volmarg.github.io/docs/general/installation/docker/information

#### Post any additional information about the project that you know is important 
Did not find it on dockerhub. PMS is a dashboard for managing personal items much like businesses manage with CRM/ERP solutions.

**Comment by Roxedus** [comment]
The docs tells the user to build the container themselves, unfortunately not suitable for CA.
