### ISSUE TITLE
CA Template Request - TwitchAutomator

### ISSUE THREAD

**Issue by Serph91P** [selfhosters/unRAID-CA-templates#335]
**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/MrBrax/TwitchAutomator
https://hub.docker.com/r/mrbrax/twitchautomator

#### Post any additional information about the project that you know is important 
what would be needed to get the docker setup running with the correct permissions so that it catually can write files?

**Comment by nwithan8** [comment]
This application is available on CA.
