### ISSUE TITLE
CA Template Request - beets-audible

### ISSUE THREAD

**Issue by wickedweasel** [selfhosters/unRAID-CA-templates#338]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
[beets-audible](https://github.com/seanap/beets-audible)

#### Post any additional information about the project that you know is important 
This container is intended to be used in conjunction with the [auto-m4b](https://github.com/seanap/auto-m4b) docker.  The auto-m4b docker is not available in CA but was easily converted when found on DockerHub.

**Comment by Roxedus** [comment]
Project isnt a built, ready to go container.
