### ISSUE TITLE
CA Template Request - InvenTree

### ISSUE THREAD

**Issue by formless63** [selfhosters/unRAID-CA-templates#342]
**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/inventree/inventree
https://github.com/inventree/InvenTree

#### Post any additional information about the project that you know is important 
https://inventree.readthedocs.io/en/latest/start/intro/

**Comment by nwithan8** [comment]
This app requires five separate Docker containers, and therefore is difficult to make into an Unraid template.
