### ISSUE TITLE
CA Template Request - Mastodon

### ISSUE THREAD

**Issue by REKTorSET** [selfhosters/unRAID-CA-templates#345]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/tootsuite/mastodon
https://github.com/mastodon/mastodon

#### Post any additional information about the project that you know is important 
This application is often split into multiple docker containers, but should be able to use redis and postgresql from currently available sources.

**Comment by catduckgnaf** [comment]
Mastodon is there now, if we could close this request
