### ISSUE TITLE
CA Template Request - bitwarden_rs

### ISSUE THREAD

**Issue by D4M4EVER** [selfhosters/unRAID-CA-templates#35]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/bitwardenrs/server/
https://github.com/dani-garcia/bitwarden_rs

#### Post any additional information about the project that you know is important 
It's the best self hosted password vault.

**Comment by christronyxyocum** [comment]
Should have this wrapped up tonight.

**Comment by D4M4EVER** [comment]
Thank you, I forgot to add on here other day and did not see it listed by anyone else.

**Comment by christronyxyocum** [comment]
https://github.com/selfhosters/unRAID-CA-templates/pull/37
