### ISSUE TITLE
CA Template Request - Hammond

### ISSUE THREAD

**Issue by formless63** [selfhosters/unRAID-CA-templates#350]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/akhilrex/hammond/tags
https://github.com/akhilrex/hammond

#### Post any additional information about the project that you know is important 
Looks like no external db required.

**Comment by bravohotel91** [comment]
This project has not been actively developed since 2022. But it seems like there are some forks but development seems intermittent. Should we pursue this issue?

**Comment by nwithan8** [comment]
According to this comment, the original project is no longer maintained (commit history seems to support this):
https://github.com/AlfHou/hammond?tab=readme-ov-file#about-the-project

^ This fork, however, seems to be very active with its own Docker image. If we were to build a template for this app, we would use this fork.

**Comment by bravohotel91** [comment]
Thanks. I'll take a look later and try to get one built.

**Comment by Roxedus** [comment]
This exists in CA
