### ISSUE TITLE
CA Template Request - Tiddlywiki

### ISSUE THREAD

**Issue by drpeppershaker** [selfhosters/unRAID-CA-templates#356]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**

https://hub.docker.com/r/elasticdog/tiddlywiki

https://github.com/Jermolene/TiddlyWiki5

#### Post any additional information about the project that you know is important 

I'm not the maintainer of either of these.

**Comment by catduckgnaf** [comment]
I believe this is there now, close request?
