### ISSUE TITLE
CA Template Request - PrivateBin

### ISSUE THREAD

**Issue by D4M4EVER** [selfhosters/unRAID-CA-templates#36]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/privatebin/nginx-fpm-alpine/dockerfile
https://github.com/PrivateBin/PrivateBin

#### Post any additional information about the project that you know is important 
<info here>

**Comment by jrdnlc** [comment]
Done #43

**Comment by D4M4EVER** [comment]
Thank you. You guys are awesome.
