### ISSUE TITLE
CA Template Request - PartDB

### ISSUE THREAD

**Issue by chuckygoodguy** [selfhosters/unRAID-CA-templates#363]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/jbtronics/part-db1
https://github.com/Part-DB/Part-DB-symfony

#### Post any additional information about the project that you know is important 
<info here>

**Comment by nwithan8** [comment]
This application is available in CA.
