### ISSUE TITLE
CA Template Request - Plex Orphaned Files

### ISSUE THREAD

**Issue by TheRealMetroid1** [selfhosters/unRAID-CA-templates#385]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**
<links here>
https://hub.docker.com/r/jakewharton/plex-orphaned-files
https://github.com/JakeWharton/plex-orphaned-files

#### Post any additional information about the project that you know is important 
<info here>

**Comment by nwithan8** [comment]
It looks like you can certainly install this as a Docker container, but would need to shell into the container and run a CLI command to actually start the underlying application. That, combined with more than 2 years of inactive development, makes me question to worthiness of creating an Unraid template for this application.

**Comment by TheRealMetroid1** [comment]
Yeah, it seemed like a good idea at the time. I found Webtools-NG which did a better job. I was hoping to the docker container locally instead of on another device but the other software I found worked fine from another device reading a network share. I believe that it would be best to close this. Thank You!
