### ISSUE TITLE
CA Template Request - Sherlock

### ISSUE THREAD

**Issue by bradtn** [selfhosters/unRAID-CA-templates#441]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**
Check out our guide: [Writing a template compatible for Unraid - Selfhosters.net](https://selfhosters.net/docker/templating/templating/)

***

**Please add the dockerhub repo link and github/gitlab link below**

https://github.com/sherlock-project/sherlock

#### Post any additional information about the project that you know is important 
<info here>

**Comment by nwithan8** [comment]
There is not a Docker image of Sherlock on Docker Hub or GitHub that can be used in an Unraid template. The Docker instructions in Sherlock's documentation refer to building the image locally.
