### ISSUE TITLE
CA Template Request - Graylog

### ISSUE THREAD

**Issue by jimphreak** [selfhosters/unRAID-CA-templates#45]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/graylog/graylog/
http://docs.graylog.org/en/stable/pages/installation/docker.html

#### Post any additional information about the project that you know is important 
<info here>

**Comment by gilbN** [comment]
added https://github.com/selfhosters/unRAID-CA-templates/pull/54
