### ISSUE TITLE
Podsync - Needs improvement on the template otherwise will be removed

### ISSUE THREAD

**Issue by Squidly271** [selfhosters/unRAID-CA-templates#462]
Please 

1. Check the templates that are being published have ports defined that are required.  This doesn't
2. Add in at least basic instructions if special set up needs to be done to get it to work.  IE: template as is creates a config.toml directory and doesn't mention anywhere that you need to create a FILE for the container to work

**Comment by nwithan8** [comment]
Thank you for reporting this @Squidly271 , we'll get it sorted away immediately.
