### ISSUE TITLE
CA Template Request - Spacebar Chat Server

### ISSUE THREAD

**Issue by Shiroe93** [selfhosters/unRAID-CA-templates#510]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

https://hub.docker.com/r/spacebarchat/server

### Link to documentation

https://docs.spacebar.chat/setup/server/

### Link to source code

https://github.com/spacebarchat/server

**Comment by Shiroe93** [comment]
I've tried to build a template myself with some help from the unraid reddit community but when I select the template in the drop down menu it's completely blank so I suppose I'm missing something 
`<?xml version="1.0"?>
<Container version="3.9">
    <Name>spacebarchat</Name>
    <Repository>spacebarchat/server:latest-sqlite</Repository>
    <Registry>https://hub.docker.com/r/spacebarchat/server</Registry>
    <Branch>
        <Tag>latest-sqlite</Tag>
        <TagDescription>Latest stable release with SQLite support</TagDescription>
    </Branch>
    <Network>bridge</Network>
    <WebUI>http://[IP]:[PORT:3001]/</WebUI>
    <Shell>bash</Shell>
    <Privileged>false</Privileged>
    <Branch>
        <Tag>latest-postgressql</Tag>
        <TagDescription>Latest stable release with PostgreSQL support</TagDescription>
    </Branch>
    <Branch>
        <Tag>latest-sqlite-amd64</Tag>
        <TagDescription>Latest stable release with SQLite support for AMD64</TagDescription>
    </Branch>
    <Branch>
        <Tag>latest-postgressql-amd64</Tag>
        <TagDescription>Latest stable release with PostgreSQL support for AMD64</TagDescription>
    </Branch>
    <Branch>
        <Tag>latest-sqlite-arm64</Tag>
        <TagDescription>Latest stable release with SQLite support for ARM64</TagDescription>
    </Branch>
    <Branch>
        <Tag>latest-postgressql-arm64</Tag>
        <TagDescription>Latest stable release with PostgreSQL support for ARM64</TagDescription>
    </Branch>`

**Comment by nwithan8** [comment]
@Shiroe93 Hello from Reddit (u/grtgbln). Feedback loop is going to be a lot easier here than on that Reddit thread. I'll test this out on my machine and see if I can help.

**Comment by Shiroe93** [comment]
Thanks 
let me know if you need anything

**Comment by Shiroe93** [comment]
i have to fill this with my value or are these variable that will be replace once i complete conging for the ui?
![immagine](https://github.com/user-attachments/assets/c9d6aa71-43e7-45a9-a0e9-6994c26a11d4)
i aked you because right know the web ui doesn't open
side note: the link you used for the icon doesn't show anything 
![immagine](https://github.com/user-attachments/assets/a00694f2-6571-4219-ba7f-795198173c32)

**Comment by nwithan8** [comment]
> i have to fill this with my value or are these variable that will be replace once i complete conging for the ui? ![immagine](https://private-user-images.githubusercontent.com/56954468/359095211-c9d6aa71-43e7-45a9-a0e9-6994c26a11d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODQyMjQsIm5iZiI6MTcyNDA4MzkyNCwicGF0aCI6Ii81Njk1NDQ2OC8zNTkwOTUyMTEtYzlkNmFhNzEtNDNlNy00NWE5LWEwZTktNjk5NGMyNmExMWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMmFhNmQxNzNjODAzZDU5NTk5NTgzMGVlMTk0MmVhZmI4YTUwZjU2ODE0ZGIzMzRkNWQ4ZmEzMGY1NGYwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6E3jY7lDVef-6wVBCibD6cHdqi7MgNs3ljNbFjQb6SY) i aked you because right know the web ui doesn't open and after 2 minutes the container stops on it's own
> 
> side note: the link you used for the icon doesn't show anything ![immagine](https://private-user-images.githubusercontent.com/56954468/359096137-a00694f2-6571-4219-ba7f-795198173c32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwODQyMjQsIm5iZiI6MTcyNDA4MzkyNCwicGF0aCI6Ii81Njk1NDQ2OC8zNTkwOTYxMzctYTAwNjk0ZjItNjU3MS00MjE5LWJhN2YtNzk1MTk4MTczYzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE2MTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ODUyNDQxOTAwZGI3ZTA3YWE1NGU2NGQwYzYwYWUzMmQzMWVhM2E1NzUxOWJkYzY5MjI5YjdlMDAwMDkxY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3fEitjj24gZKiD4cMFMQMXieU73UNI8bn90ZLau1umQ)

You would have to fill out that "Database connection", those are just placeholder values.

The icon won't load because it points to an image that does not (yet) exist.

**Comment by nwithan8** [comment]
> Understood i have to look into how to create a PostreSQL database because I've never done it before
> 
> edit found a tutorial but the spacebar docs don't mention any specific version do you have any suggestions? unraid has version 12, 13, 14, 15, 16, and alpine (wich i suppose is based on alpine linux)

The docs for Spacebar's Docker Compose use 15

**Comment by Shiroe93** [comment]
i must have missed it 
thank you

**Comment by Shiroe93** [comment]
i have istalled the postgres 15 container then tried with the default postgres database and with one created by me (user and database with all the permissions granted) but the spacebar container keeps stopping on his own 
can't see any obvious error in the logs 
![immagine](https://github.com/user-attachments/assets/affbdcda-dbee-4517-8594-35e0ec72992b)

this are the comand i used in postgres to crate the new user and database 
postgres=# create database mydb;
postgres=# create user myuser with encrypted password 'mypass';
postgres=# grant all privileges on database mydb to myuser;
and all went without issues

**Comment by nwithan8** [comment]
> i have istalled the postgres 15 container then tried with the default postgres database and with one created by me (user and database with all the permissions granted) but the spacebar container keeps stopping on his own error in the log says "uri malformed"
> 
> this are the comand i used in postgres to crate the new user and database postgres=# create database mydb; postgres=# create user myuser with encrypted password 'mypass'; postgres=# grant all privileges on database mydb to myuser; and all went without issues

Would you mind sharing the "Database connection" URL that you are using?

**Comment by Shiroe93** [comment]
postgres://shiroe:mypassword@192.168.50.12:5432/spacebar ( name a gave to the database)

**Comment by Shiroe93** [comment]
i tried search in the spacebar docs but it seems correct and i checked inside postgres console and the database is working and accessible with the correct credential

**Comment by Shiroe93** [comment]
after solving another 3-4 error i have finally manage to make it start

**Comment by nwithan8** [comment]
> after solving another 3-4 error i have finally manage to make it start

Oh, please do share.

**Comment by Shiroe93** [comment]
Two major problem had arise 
1 postgres connection url did not like password with special characters 
2 even if you grant al privileges on a database for a specific user do to new security feature in postgres 15 you also  have to grant authority to schema public separately 

`CREATE DATABASE EXAMPLE_DB;
CREATE USER EXAMPLE_USER WITH ENCRYPTED PASSWORD 'Sup3rS3cret';
GRANT ALL PRIVILEGES ON DATABASE EXAMPLE_DB TO EXAMPLE_USER;
\c EXAMPLE_DB postgres
# You are now connected to database "EXAMPLE_DB" as user "postgres".
GRANT ALL ON SCHEMA public TO EXAMPLE_USER;
`
(All in lower case)

 Now i only have to hope that I'm able to understand the rest of the docs and complete deployment but the container part is done so i think you can consider it as working 
It The first time in years that i find something so articulate that hasn't had a tutorial been made

**Comment by Shiroe93** [comment]
can confirm is working even if unfortunately it didn't have the voice chat feature i was looking for (not implemented yet) so it's not a full discord replacement 
for those who might been interested i'm currently looking into Mirotalk that is more similar to google meet
