### ISSUE TITLE
CA Template Request - Morphos Server

### ISSUE THREAD

**Issue by ggfevans** [selfhosters/unRAID-CA-templates#519]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

https://ghcr.io/danvergara/morphos-server

### Link to documentation

https://github.com/danvergara/morphos?tab=readme-ov-file#morphos-server

### Link to source code

https://github.com/danvergara/morphos

**Comment by ggfevans** [comment]
Morphos is a project that allows you to convert files privately. It supports many formats and more to come. Version 0.6.0 just dropped adding an API so others system can interact with it and support for ebooks.

Reddit thread for more context: https://www.reddit.com/r/selfhosted/comments/1fmdaiz/morphos_selfhosted_file_converter_server/

**Comment by nwithan8** [comment]
This has been added to CA via a separate maintainer, but thank you!
