### ISSUE TITLE
CA Template Request - hotio hddtemp2influxdb

### ISSUE THREAD

**Issue by jimphreak** [selfhosters/unRAID-CA-templates#52]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/hotio/hddtemp2influxdb

**Comment by Roxedus** [comment]
Waiting on feedback on hotio/docker-hddtemp2influxdb#1

**Comment by hotio** [comment]
I myself use this logo
https://raw.githubusercontent.com/hotio/unraid-icons/master/influxdbupload.png
