### ISSUE TITLE
CA Template Request - jellyfin_with_request

### ISSUE THREAD

**Issue by soultaco83** [selfhosters/unRAID-CA-templates#528]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

https://hub.docker.com/r/soultaco83/jellyfin_with_request

### Link to documentation

https://github.com/jellyfin/jellyfin

### Link to source code

https://github.com/jellyfin/jellyfin

**Comment by soultaco83** [comment]
I made a template and messaged squid via unraid forums but then I found this so posted here. 
https://github.com/soultaco83/unraid-templates/blob/master/jellyfin_with_request/jellyfin_with_request.xml

This docker is created using the Jellyfin-packaging
https://github.com/soultaco83/jellyfin-packaging

I pull latest commits from the web and server. Prebundle my plugin and updated webui with the new tab created. 
https://github.com/soultaco83/Jellyfin_requests_plugin
https://github.com/soultaco83/jellyfin-server
https://github.com/soultaco83/jellyfin-web-requeststab

Github is set to pull latest commits every satruday at 2am and then build and push updated docker at 3am.

**Comment by nwithan8** [comment]
Why not just have users install the plugin into Jellyfin? Is there a need to have a whole fork of Jellyfin for this?

Also, what CI/CD systems have you put in place to ensure that this Docker application doesn't go stale (stays in sync with the main Jellyfin upstream project)?

**Comment by soultaco83** [comment]
I'm honestly not sure how many people would find this useful. I have seen a few requests for a tab to be added to jellyfin so that users have have ombi/jellyseer integrated directly in.
So far these changes have worked for me so I thought might as well make it public. 

User can install the plugin themselves but they need to use the webui that is in my repo as it has the updated files to include the new tab on the homepage and thought might as well include the plugin too. Updating the existing jellyfin docker to just include everything made sense to me.

I forked the whole of jellyfin web and server as I had pr's merged that are not in master branch yet. Only ones right now are for webui which are listed on the repo, but they are hiding trailers tab in movies unless trailers exist, adding a chapters button to the player and better scaling of subtitles to match screen resolution.
No untested pr's would get pushed to the docker main without testing by me and my users.

I have a GitHub action on each repo that syncs the master branches to the master branch of server and web. Example of one. And then a new docker is build and pushed to the hub every Saturday with the latest changes.
```'name: Sync with Jellyfin Web Repository

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jellyfin-web-requests repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ secrets.WORKFLOW }}

      - name: Configure git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Add upstream remote
        run: git remote add upstream https://github.com/jellyfin/jellyfin-web.git

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Merge upstream changes to master
        run: |
          git checkout master
          git merge upstream/master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW }}

      - name: Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The workflow "Sync with Jellyfin Web Repository" has failed!'```

**Comment by soultaco83** [comment]
If it is determined to not be necessary. Just let me know. Thank you.

**Comment by nwithan8** [comment]
I can't control whether you create the application or not, I just want to make sure that it's going to be a maintained project so we don't pollute the Community Apps Store with templates for abandonware.

**Comment by soultaco83** [comment]
Closing.
