### ISSUE TITLE
CA Template Request - ChartDB

### ISSUE THREAD

**Issue by SalmonSays** [selfhosters/unRAID-CA-templates#533]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

https://github.com/chartdb/chartdb/pkgs/container/chartdb

### Link to documentation

https://www.chartdb.io/?ref=github_readme

### Link to source code

https://github.com/chartdb/chartdb

**Comment by nwithan8** [comment]
This has been contributed by a separate party

**Comment by SalmonSays** [comment]
> This has been contributed by a separate party

Can you point me in the right direction? I don't see it as either an open or closed issue here by that name and it's not already on Unraid's CA system.
