### ISSUE TITLE
CA Template Request - Ambar

### ISSUE THREAD

**Issue by ark-** [selfhosters/unRAID-CA-templates#56]
**Please add the dockerhub repo link and github/gitlab link below**
https://github.com/RD17/ambar
https://ambar.cloud/docs/installation-docker/

#### Post any additional information about the project that you know is important 
They have a "Building the docker images yourself" section which could be of use.

**Comment by Roxedus** [comment]
This application requires multiple containers, one of them being ElasticSearch which needs changes to the host.

**Comment by Roxedus** [comment]
The complexity has increased since last time, we wont support this.
