### ISSUE TITLE
CA Template Request - <unifi-poller>

### ISSUE THREAD

**Issue by Blindside995** [selfhosters/unRAID-CA-templates#8]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
<https://hub.docker.com/r/golift/unifi-poller/dockerfile>

#### Post any additional information about the project that you know is important 
<Influxdb & Grafana are required for this. Unifi gear is also a requirement.>

**Comment by gilbN** [comment]
added, should be available in 30 minutes

**Comment by Blindside995** [comment]
Thanks, GibN! 😃
