### ISSUE TITLE
CA Template Request - ArchiveBox

### ISSUE THREAD

**Issue by GlassedSilver** [selfhosters/unRAID-CA-templates#80]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/nikisweeting/archivebox/
https://github.com/pirate/ArchiveBox
https://archivebox.io/

#### Post any additional information about the project that you know is important 
0.4 will be a huge revamp with lots of new features added, however there is a weird lack of easy to setup, versatile web archiving tools of this caliber out there. This is more than your average .warc exporting crawler.

Way more.

**Comment by jrdnlc** [comment]
I’ll take care of this one. Should be able to do it by tonight or tomorrow.

**Comment by GlassedSilver** [comment]
Any update on this? Unfortunately I have not yet deployed the software myself, so I'm afraid I cannot really help out here, but the project is on github, so I wager the dev would maybe be kind enough to help out if necessary?

**Comment by jrdnlc** [comment]
I’m still testing it but it’s done. Will submit the template once I decide it’s good to go.

**Comment by Roxedus** [comment]
We have been busy, we recently released [selfhosters.net](https://selfhosters.net/).
You also mentioned 0.4, so figured we could wait on that, seems it sounds like we would need to change the template for that anyway.

**Comment by GlassedSilver** [comment]
> We have been busy, we recently released [selfhosters.net](https://selfhosters.net/).
> You also mentioned 0.4, so figured we could wait on that, seems it sounds like we would need to change the template for that anyway.

Well there is a pre-release build, it‘s not recommended to use it for private pages yet, but from what I read ready to go in a beta readiness sense. The API changes seem to be done, so I suspect the reworking is going to be internal workings and taking the beta 0.4 release would be a solid base for an eventual final 0.4.

I may be wrong about this, but that‘s how I understood it.

Maybe one could release it with the same warning the dev put up and mark it in CA as beta? Could possibly attract people with more programming skills than I have to help work on the project, since the security reworking seems a few more months off, but I have a lot that I would love to archive already with the given security warnings in mind regardless. Websites are dying everyday. :/

Anyhow thank you for all your work and I‘m very much looking forward to having another repertoire of information around unRAID, absolutely enjoying that the ecosystem is getting so strong and community support for unRAID is where it‘s at.

I‘m very very grateful for all that you and everyone else is doing and I have a few projects of my own that I might document sometime for more people to make use of once everything has proven itself as solid and stable. Definitely wanna give back with my own capabilities. (:

**Comment by jrdnlc** [comment]
This is on CA now.
