### ISSUE TITLE
CA Template Request - Healthchecks

### ISSUE THREAD

**Issue by cbackas** [selfhosters/unRAID-CA-templates#84]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
https://hub.docker.com/r/linuxserver/healthchecks
https://github.com/linuxserver/docker-healthchecks

**Comment by Roxedus** [comment]
Wont do. If linuxserver wants it in unraid, they will add it themself

**Comment by gilbN** [comment]
@cbackas create an issue on the repo and ask if they can.

**Comment by cbackas** [comment]
Roger that @gilbN
