### ISSUE TITLE
CA Template Request - <application name>

### ISSUE THREAD

**Issue by Blindside995** [selfhosters/unRAID-CA-templates#9]
### NOTE
 **If you know how to make unraid container templates PR's are welcome!**

***

**Please add the dockerhub repo link and github/gitlab link below**
<https://hub.docker.com/r/invoiceninja/invoiceninja/>

#### Post any additional information about the project that you know is important 
<The GitHub page has a lot of info on it that is important to know. This container might be kind of tricky given all the things it requires. You can always use the hosted version of this service for free. In the past I had tried making a template for this container but failed. See more info at https://github.com/invoiceninja/invoiceninja>

**Comment by gilbN** [comment]
https://hub.docker.com/r/anojht/invoiceninja/dockerfile

Will use this one instead. Has nginx inside

**Comment by gilbN** [comment]
added

**Comment by gilbN** [comment]
@Roxedus  see anything wrong in the template? Hasnt been added to CA yet

**Comment by gilbN** [comment]
Think I found the error

**Comment by Roxedus** [comment]
You did, its there now
Squidly271/AppFeed@10b8fd7
